language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  - travis_retry pip install tox==1.8.1
script:
  - travis_retry tox
notifications:
  email:
    recipients:
      - wosc@wosc.de
