language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=py27
install:
  - travis_retry pip install tox==2.9.1
script:
  - travis_retry tox
notifications:
  email:
    recipients:
      - wosc@wosc.de
